### ISSUE TITLE
Seems a bug in 1.8.0

### ISSUE THREAD

**Issue by irriss** [vchaptsev/vue-yandex-metrika#14] opened 2019-04-26 09:38 UTC
Hello,

Thanks for this package.

After upgrading to 1.8.0 got this bug in console

Uncaught SyntaxError: Unexpected token <
vue-yandex-metrika.js?932e:1 
Uncaught ReferenceError: Ya is not defined
    at u (vue-yandex-metrika.js?932e:1)
    at HTMLScriptElement.eval (vue-yandex-metrika.js?932e:1)

1.7.3 does not have this issue.

Could you help fixing it?

**Comment by irriss** [comment] 2019-04-26 09:46
actually the error is gone if I add new param explicitly

scriptSrc: 'https://mc.yandex.ru/metrika/tag.js'

strange that default value isnt picked up

**Comment by konart** [comment] 2019-05-24 12:43
This one should be either a documented feature or an issue to be fixed.

**Comment by cranx** [comment] 2019-05-30 14:07
+1 
Why does scriptSrc should be an option? 
I guess `https://mc.yandex.ru/metrika/tag.js` must be default value at least

**Comment by Bargamut** [comment] 2019-06-30 12:51
You can read [this](https://github.com/vchaptsev/vue-yandex-metrika/pull/13).
It's not a bug, it's a feature. )

But it will be better if this option will have value by default, of course.

**Comment by vchaptsev** [comment] 2019-07-21 18:25
Fixed by @0311snitch here: #15 
New version [1.8.1](https://www.npmjs.com/package/vue-yandex-metrika) is available.

**Closed as completed by vchaptsev** 2019-07-21 18:25 UTC
